#!/bin/bash
set -euo pipefail

declare DOCKER_USER="hkjn"
declare DOCKER_IMAGE="docker"
declare CPU_ARCH="$(uname -m)"
declare BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
declare BUILD_DIR="$(mktemp -d)"
declare BASE_IMAGE="hkjn/alpine:${CPU_ARCH}"
declare TAG="${DOCKER_USER}/${DOCKER_IMAGE}:${CPU_ARCH}"
declare NO_PUSH=${NO_PUSH:-""}
declare -A DOCKER_ARCHS
DOCKER_ARCHS[x86_64]=x86_64
DOCKER_ARCHS[armv7l]=armhf
declare DOCKER_ARCH=${DOCKER_ARCHS[$CPU_ARCH]}

cd ${BASE_DIR}
sed "s|{{BASE_IMAGE}}|${BASE_IMAGE}|g" Dockerfile.in > $BUILD_DIR/Dockerfile
cp docker-entrypoint.sh ${BUILD_DIR}

echo "Building ${TAG} in ${BUILD_DIR}.."
docker build -t ${TAG} --build-arg docker_arch=${DOCKER_ARCH} ${BUILD_DIR}
[[ "$NO_PUSH" ]] || docker push $TAG
